---
services:
  dimos:
    image: dimos:latest
    build: ./../../
    env_file:
      - ./../../.env
    mem_limit: 8048m
    stdin_open: true
    tty: true
    volumes:
      - ./../../assets:/app/assets
    ports:
      - "5555:5555"
    # command: [ "python", "-m", "tests.test_agent" ] 
    # ^^ Working Sanity Test Cases - Expand to Agent Class
    #
    # command: [ "python", "-m", "dimos.types.videostream" ] 
    # ^^ Working Skeleton - Needs Impl.
    #
    # command: [ "python", "-m", "dimos.types.media_provider" ] 
    # ^^ Working Instance - Needs Tests. 
    # 
    # command: [ "python", "-m", "dimos.web.edge_io" ] 
    # ^^ Working Instance - Needs Tests. 
    # 
    command: [ "python", "-m", "demos.agent_manip_flow_test" ] 

# ----
# TO RUN:
#   docker build -f ./Dockerfile -t dimos ../../ && docker compose up
# GO TO:
#   127.0.0.1:5555 (when flask server fixed)
# ----

#  video-service:
#    build: ./video-service
#    image: video-service:latest
#    volumes:
#      - ./../../assets:/app/dimos-env/assets
#    ports:
#      - "23001:23001"
